wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.17.1
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1744093381
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 95
      - 98
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 95
      - 98
      3:
      - 13
      - 14
      - 23
      4: 3.9.13
      5: 0.17.1
      6: 4.44.2
      8:
      - 5
      13: linux-x86_64
